### ISSUE TITLE
Setup IRC hook for commits

### ISSUE THREAD

**Issue by cynthia** [w3c/touch-events#1]
Would be nice to setup a IRC hook for commits. Channel should be #touchevents at irc.w3.

**Comment by cynthia** [comment]
@sideshowbarker @shepazu ?

**Comment by sideshowbarker** [comment]
should be all set up now

**Comment by AFBarstow** [comment]
thanks @sideshowbarker !

**Comment by RByers** [comment]
I've seen this working.
