### ISSUE TITLE
TouchEvent and Touch should have constructors

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#10]
Most other event types have constructors defined these days.  TouchEvent should as well.  initTouchEvent was never standardized (though supported by some browsers), I suggest we go straight to standardizing a TouchEvent constructor.

Perhaps Touch and TouchList should also have constructors in favor of document.createTouch/createTouchList?

**Comment by patrickhlauke** [comment]
I think that's a substantive change, though. Is that in scope for errata, or - as is my hunch - does this need to be a version 2.0 (with associated WG etc overhead)?

**Comment by RByers** [comment]
Right we could only do this in some future v2.  I figured it was worth making a list of the things we might want in some future version of the spec.  WDYT?

**Comment by patrickhlauke** [comment]
Oh sure, in that context, it makes sense for consistency.

**Comment by RByers** [comment]
Perfect, thanks (I was just trying to figure out what the github way of categorizing bugs was - got distracted by 'labels').

**Comment by RByers** [comment]
History from WebEvents WG which originally resolved to add a constructor: http://www.w3.org/2010/webevents/track/issues/23

initTouchEvent was never standardized because WebKit's (and now blink's) implementation is bizarre (has 4 unused params): https://bugs.webkit.org/show_bug.cgi?id=60612

**Comment by RByers** [comment]
I'd like to do this because otherwise there's no way to create a TouchEvent with any new fields in UIEvent (such as [sourceDevice](rbyers.github.io/InputDevice/inputdevice.html)), or any of the new extension values (radius, etc.).

In fact, I suspect there's so little usage of createTouch/createTouchList/initTouchEvent that we will be able to remove them completely once there is a constructor (collecting usage stats in chromium now).

**Comment by RByers** [comment]
Fixed in #16

**Comment by RByers** [comment]
For the record, here are bugs tracking implementation in [Blink](https://code.google.com/p/chromium/issues/detail?id=508675) and [WebKit](https://bugs.webkit.org/show_bug.cgi?id=147740)
