### ISSUE TITLE
Define the ontouch* event handler attributes

### ISSUE THREAD

**Issue by foolip** [w3c/touch-events#11]
Specs need to define these explicitly, as not all events have the corresponding event handler attributes. See Fullscreen for an example: https://fullscreen.spec.whatwg.org/#api

Blink has `ontouchstart`, `ontouchend`, `ontouchmove` and `ontouchcancel` on the `Document`, `Element` and `Window` interfaces.

**Comment by RByers** [comment]
We should probably do this exactly like [in Pointer Events](https://w3c.github.io/pointerevents/#extensions-to-the-globaleventhandlers-interface).  Should be trivial for anyone interested in supplying a PR.  When doing this we should also add tests to web-platform-tests (or file a separate issue to track that).

**Comment by RByers** [comment]
Chromium [bug 518850](https://code.google.com/p/chromium/issues/detail?id=518850) tracks moving these from `Document`, `Element` and `Window` to `GlobalEventHandlers`.

**Comment by foolip** [comment]
`GlobalEventHandlers` in defined by https://html.spec.whatwg.org/#globaleventhandlers so either they'll have to be defined by the HTML spec, or another spec needs a `partial interface GlobalEventHandlers`. I don't know if that works or not, it's unusual in that `GlobalEventHandlers` isn't itself a "proper" interface, but the target of `implements`.

Also note that `GlobalEventHandlers` is implemented by `Document`, `HTMLElement` and `Window`, not `Element`. Moving the attributes from `Element` to `HTMLElement` might be possible, but if not a new `TouchEventHandlers` or similar would be the only option.

**Comment by foolip** [comment]
Looks like it's been done before: https://w3c.github.io/pointerevents/#extensions-to-the-globaleventhandlers-interface

**Comment by foolip** [comment]
Uh, I didn't even notice that this was already merged and live:
http://w3c.github.io/touch-events/#extensions-to-the-globaleventhandlers-interface

Please ignore everything I've said.

**Comment by RByers** [comment]
Don't worry about the fact that this has already landed, we can easily still make improvements here (and in the PEWG spec).  Note that `SVGElement` [also implements](https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement) `GlobalEventHandlers`, so I think moving the definition from `Element` to `GlobalEventListeners` is almost completely a no-op.  Can you think of any realistic use cases which might notice?  I guess this is probably really a discussion for the [blink bug](https://code.google.com/p/chromium/issues/detail?id=518850).

**Comment by foolip** [comment]
Oh right, `SVGElement` is doing this too now. It's hard to see much consistency when it comes to having APIs on `Element` vs. `HTMLElement`+`SVGElement`. In this case following the example of pointer events seems fine until there's a reason to do otherwise.
