### ISSUE TITLE
Switch default branch to gh-pages and delete master

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#15]
Active work is now happening in the gh-pages branch, so the default branch should be switched and 'master' deleted to avoid confusion.  I don't appear to have the necessary permissions to do this.  @AFBarstow?

**Comment by patrickhlauke** [comment]
could you hold off as I'm now in the middle of re-porting my errata from https://github.com/w3c/touch-events/pull/3 which seem to have fallen by the wayside in the recent change?

**Comment by shepazu** [comment]
Default branch is now gh-pages.

Deleted master branch.
