### ISSUE TITLE
Redirect "latest editors draft" link to github.

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#18]
The [currently published spec](http://www.w3.org/TR/touch-events/) points to [https://dvcs.w3.org/hg/webevents/raw-file/v1/touchevents.html](https://dvcs.w3.org/hg/webevents/raw-file/v1/touchevents.html) as the latest editors draft.

As [for the pointer-events spec](https://lists.w3.org/Archives/Public/public-pointer-events/2015AprJun/0104.html), we should get GitHub redirection setup.

@AFBarstow can you take care of this?

**Comment by RByers** [comment]
Or is @shepazu the one that needs to arrange this for us?

**Comment by cynthia** [comment]
We could probably do it ourselves if we can make use of echidna, but I'm not sure if that applies in this case considering the state of the group/spec. @AFBarstow ?

**Comment by AFBarstow** [comment]
@cynthia @RByers given a CG can't formally publish TRs, I think what we want to do here is to redirect the Hg ED http://dvcs.w3.org/hg/webevents/raw-file/v1/touchevents.html to http://w3c.github.io/touch-events/touchevents.html. Correct?

AFAIK, that redirection can only be done by w3c staff so I will submit a request after you confirm the above is what we want.

**Comment by cynthia** [comment]
Ah, that was what I was afraid of. Ignore my comment about echidna in that case. :)

**Comment by AFBarstow** [comment]
@cynthia echnida comment ignored ;-)

(Actually, re the redirect, after touchevents.html is renamed to index.html, the Hg ED will redirect to http://w3c.github.io/touch-events/. )

**Comment by RByers** [comment]
Yep, sounds right to me.

**Comment by AFBarstow** [comment]
This redirect now works.

**Comment by RByers** [comment]
Thanks Art!
