### ISSUE TITLE
Enable GitHub notifications to public-touch-events

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#19]
As for other W3C groups, public-touch-events@w3.org should get notifications of any changes in GitHub. Doug, can you do this please?

Looks like notifications are already going to IRC (#touchevents).

**Comment by AFBarstow** [comment]
On July 30 I submitted a request to do this and today I received a notification that the request has been done. (I'll leave this open until we see this repo's traffic get forwarded to p-touch-events list.)

**Comment by AFBarstow** [comment]
Closing (this Issue has been addressed).
