### ISSUE TITLE
Reformat code

### ISSUE THREAD

**Issue by cynthia** [w3c/touch-events#2]
The master source for the spec is pretty poorly formatted - should fix this. Think the agreement was to do 4 space indentation, but the rest is a bit fuzzy.

**Comment by cynthia** [comment]
Probably only needed for master, since that's the only branch that will get active updates.

**Comment by patrickhlauke** [comment]
> Probably only needed for master, since that's the only branch that will get active updates.

And v1-errata ...

**Comment by RByers** [comment]
@cynthia are you still planning on doing anything here?  This doesn't really bother me (but I've been doing some little cleanups as I go).

**Comment by cynthia** [comment]
Are all the bigger edits in? I think Patrick and you did some stuff, but I could go in and do a full sweep if there aren't any big changes in progress that might cause merge conflicts later.

**Comment by RByers** [comment]
I've got [two pull requests](https://github.com/w3c/touch-events/pulls) open right now.  Maybe once those land?  Not urgent or anything, was just trying to clean up open issues.

**Comment by cynthia** [comment]
Ok, then it's probably safer to do after the two PRs are merged.

**Comment by RByers** [comment]
@cynthia All open pull requests have now landed, so now would be a good time to do reformatting if you're still interested.

**Comment by cynthia** [comment]
@RByers Cool, will try to slide a PR in this week.

**Comment by patrickhlauke** [comment]
Although there are still a few inconsistencies, overall the markup doesn't look as horrendous as i remember it. Is this still an issue, or can it be closed?
