### ISSUE TITLE
Should we keep the identifiedTouch method?

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#20]
From what I can tell, TouchList.identifiedTouch was in the original v2 draft from the beginning.  We removed it from v1 due to lack of implementations (only Mozilla).  Should we keep it in v2?  It doesn't seem to add much value to me (a linear search through the list is probably the fastest implementation for any realistic number of touch points).  But if the group likes it then I'm happy to keep it (and try to get it added to blink).

@mbrubeck @smaug--- any opinion?

**Comment by mbrubeck** [comment]
I think we should remove it. I agree with the reasons above.

**Comment by RByers** [comment]
Thanks Matt.  Are you going to file a Mozilla bug to deprecate / consider removing this API, or would you like me to?  At least MDN should be updated.

**Comment by mbrubeck** [comment]
Filed [bug 1188539](https://bugzilla.mozilla.org/show_bug.cgi?id=1188539) and updated MDN.

**Comment by RByers** [comment]
Great, thank you!
