### ISSUE TITLE
Delete wd and v1-errata branches?

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#24]
We've decided we're not going to publish an errata, seems like the v1-errata branch serves no purpose.  Should we delete it?  Also 'wd' doesn't seem to serve any purpose anymore either.

'v1' is still valuable to track how things have changed since original publication (though it's a little messy due to how some v1/v2 edits were authored in hg then moved to github).

**Comment by AFBarstow** [comment]
OK, so keep the v1 branch and delete the v1-errata and wd branches. Any objections?

**Comment by RByers** [comment]
Done.
RByers deleted wd at d62ea68
RByers deleted v1-errata at 9a5e800
