### ISSUE TITLE
Move touchevents.html to index.html?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#26]
Since the default branch of this repo is now gh-pages, perhaps touchevents.html should be moved to index.html so that https://w3c.github.io/touch-events/ is the "live" ED? 

WDYT? If there are no objections, I'll submit a PR.

**Comment by patrickhlauke** [comment]
That'd be my preference too...

**Comment by RByers** [comment]
Can we also leave a dummy touchevents.html behind that does a redirect?  There are a few links floating around.  If so, then renaming sounds good to me.

**Comment by AFBarstow** [comment]
RByers > Can we also leave a dummy touchevents.html behind that does a redirect?

After the rename/move, I _think_ Github will do this auto-magically. We can always do the move and then test (and add the stub file if necessary).

**Comment by RByers** [comment]
Sounds great!

**Comment by AFBarstow** [comment]
The rename has been done but there is the issue that <> now 404's. @RByers suggested using the following meta/refresh as a pattern we can use to create a new stub _touchevents.html_ file that redirects to index.html http://webmaster.iu.edu/tools-and-guides/maintenance/redirect-meta-refresh.phtml

**Comment by AFBarstow** [comment]
Ooops, it is http://w3c.github.io/touch-events/touchevents.html that now 404s.

**Comment by AFBarstow** [comment]
I created the dummy/stub touchevents.html file so http://w3c.github.io/touch-events/touchevents.html no longer 404's. Feel free to update this file.

**Comment by RByers** [comment]
Looks great, thanks!
