### ISSUE TITLE
Add tests for TouchEvent and Touch constructors

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#27]
With constructors in the spec (#10) we should add some test cases to web-platform-tests for them.

**Comment by RByers** [comment]
We'll do this as part of [implementing the constructors in blink](https://github.com/w3c/web-platform-tests/blob/master/touch-events/create-touch-touchlist.html).  It should be easy - just create a new test similar to [create-touch-touchlist](https://github.com/w3c/web-platform-tests/blob/master/touch-events/create-touch-touchlist.html) but that uses the constructor syntax instead.

**Comment by RByers** [comment]
Note (for public-touchevents) that a pull request is under review [here](https://github.com/w3c/web-platform-tests/pull/2299).  I'm not entirely sure of the process here, so please weigh in if you have advice.

**Comment by AFBarstow** [comment]
@RByers you mean how to get a w-p-t PR reviewed (and merged)? 

The <em>formal-ish</em> documentation appears to be in [w-p-t's review-process](http://testthewebforward.org/docs/review-process.html) document. 

In practice, it can help to ask for a review (especially if the commit is relatively small) in W3C's #testing IRC channel.

(I think only a few people can merge w-p-t PRs.)

**Comment by RByers** [comment]
@AFBarstow thanks!

**Comment by chong-z** [comment]
Thanks! I will land the blink code first so we can test it on Chrome build

**Comment by chong-z** [comment]
Fixed in https://github.com/w3c/web-platform-tests/pull/2299

**Comment by RByers** [comment]
Thank you!
