### ISSUE TITLE
TouchInit should perhaps include pageX and pageY

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#28]
In #10 I added a constructor for Touch.

@foolip [says](https://codereview.chromium.org/1272603003/#msg8):

> most event constructors just allow all the values to be set to anything at all, even if that's something that couldn't be produced by a real event.

I was thinking we were following the pattern from MouseEvent here (and keeping with the pattern of document.createTouch).  

[UIEvents says](https://w3c.github.io/uievents/#interface-MouseEvent):

> Note: When initializing MouseEvent objects using initMouseEvent, implementations can use the client coordinates clientX and clientY for calculation of other coordinates (such as target coordinates exposed by DOM Level 0 implementations or other proprietary attributes, e.g., pageX).

But I guess that's a little different as the UIEvents spec doesn't specify the other attributes.  Should we just let script supply `pageX` and `pageY` too?  I don't see any problem with that.

@mbrubeck any opinion?

**Comment by foolip** [comment]
Oh, so there's similar discrepancies for `MouseEvent` vs. `MouseEventInit`. I don't really feel strongly about this, it just struck me as unusual. Perhaps @annevk has strong opinions on what an event init dict should look like.

**Comment by annevk** [comment]
I think UI Events is quite broken when it comes to `MouseEvent` (UI Events is better not used as a guidance for defining events):
1. It should include the missing members.
2. Although it should not change `initMouseEvent()` arguments, it should define the method fully. Not through a note.
3. The missing members should be included in the `MouseEventInit` dictionary.

**Comment by RByers** [comment]
> It should include the missing members.

Ok, thanks - we'll do that.

> Although it should not change initMouseEvent() arguments, it should define the method fully. Not through a note.

I assume you mean `initTouchEvent`, right?  We had a big debate about this back for TEv1 - there were issues with differences of implementation and a strange API signature.  That said, I just did an httparchive search and found a surprising amount of usage of `initTouchEvent` so I agree we should just specify what Safari does.  Filed #29

**Comment by annevk** [comment]
My post was specifically about UI Events, though some of it may apply to Touch Events too. `initTouchEvent` would be sad, but if enough implementations ship it that might be a lost cause.

**Comment by RByers** [comment]
> My post was specifically about UI Events, 

Ah, ok - sorry for the confusion.  I'm not involved in trying to change the `UI Events` spec, so I'm focused here just on what we should do for `TouchEvents`.  `initTouchEvent` is a note today and it's not clear to me if the usage matters or not - we'll try to figure that out [here](https://code.google.com/p/chromium/issues/detail?id=522100).

**Comment by smaug----** [comment]
(pageX/Y are odd properties, since if MouseEvent is created by a script, pageX/Y are computed from clientX/Y values passed to ctor/init*Event and the web relies on that behavior. But I guess explicitly passing pageX/Y would be fine too)

**Comment by annevk** [comment]
That does seem to require some special logic. Perhaps even in the generic event constructor algorithm...

**Comment by RByers** [comment]
Yeah there's not going to be any getting around the fact that we have to define the logic for `MouseEvent`.  The argument here was whether we should figure how how to define the `Touch` constructor to do the same thing as for `MouseEvent`, or just require `pageX/Y` to be specified explicitly (computed by the caller instead of by the engine).

Anne convinced me we should do the latter.  Anne, are you now saying that perhaps we should do the former instead?

**Comment by annevk** [comment]
I think ideally the `TouchEvent` constructor has no magic with regards to `pageX`/`pageY` or any other properties.

**Comment by RByers** [comment]
I was all set to add these, but then Anne mentioned on another thread somewhere (that I can't find) that he's no longer convinced of the above comment.  Anne, what's your current guidance here?  Should event initializers be dumb structs that initialize every property (even when the values are technically not self consistent), or should the constructors be smart enough to initialize derived properties from the values of other properties?

Note that @choniong is in the process of adding these constructors to blink now.

**Comment by annevk** [comment]
Well, I wasn't sure it matches what browsers do. That behavior is preferable still I think, since it requires no custom logic. Though we need some custom logic for `MouseEvent` and maybe other events?

**Comment by foolip** [comment]
It looks like neither Blink nor Gecko have the `Touch` constructor yet, so this ought not be constrained by existing implementations.

**Comment by RByers** [comment]
Thanks @annevk, that makes sense.  I'm also not sure what to do about `MouseEventInit` but since `TouchInit` is new, let's do the right thing and include the computed properties `pageX` and `pageY` (even though that may be inconsistent with `MouseEventInit`).

@choniong feel free to submit a pull request with that spec tweak (or if you prefer I can make it).

**Comment by chong-z** [comment]
Sure I can do this, good place to start.
