### ISSUE TITLE
force property?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/touch-events#30]
Rumor has it that Apple's 3D touch adds a new `force` property. At the risk of opening another can of IP/patent worms, wondering if this can be considered for documentation (if it does indeed turn out to be stable). See http://www.mobilexweb.com/blog/ios9-safari-for-web-developers#update928

**Comment by AFBarstow** [comment]
This property is included in the [Touch Events Extensions Note](http://www.w3.org/TR/2013/NOTE-touch-events-extensions-20131031/)  and the [Touch Events Level 2 ED](http://w3c.github.io/touch-events/). If we have two implementations and/or have reasonable commitments to implement it, we should work toward getting the L2 spec on the REC track.

**Comment by RByers** [comment]
My iPhone 6s hasn't arrived yet, but I'm under the impression (based on discussions with Ben, eg. [here](https://twitter.com/RickByers/status/641804114922356736)) that it implements our `force` exactly as spec'd - for 3d touch and for the pencil (and so interoperable with Chrome's existing Android stylus support).

Note that Chrome has both `force` and ([until Chrome 47](https://code.google.com/p/chromium/issues/detail?id=460099)) `webkitForce` but WebKit did the right thing and implemented only `force` :-).

**Comment by RByers** [comment]
But I'm not aware of a 2nd implementation of `radiusX`, `radiusY` or `rotationAngle` yet.  There's some support for adding radius to WebKit [here](https://bugs.webkit.org/show_bug.cgi?id=133642).

**Comment by patrickhlauke** [comment]
Oops, my bad. I remembered about `radiusX`, `radiusY` and `rotationAngle`, but somehow it slipped my mind that `force` was also spec'd already. Sorry for the noise...
