### ISSUE TITLE
Convert idl to new respec format (double comma in some dictionary members)

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#31]
Some of the members of the Dictionary objects (f.ex. clientX) include ", ," (comma, space, comma) in their definitions.

(Perhaps this is some kind of bug with using ReSpec?)

**Comment by RByers** [comment]
Thanks.  Looks like specific to the [TouchInit](https://w3c.github.io/touch-events/#dictionary-touchinit-members) dictionary definition (probably my mistake when I added it).  Chong on my team is taking a look.

**Comment by mbrubeck** [comment]
This also shows up on other dictionary members with default values, like the `touches` property of `TouchEventInit`.

**Comment by chong-z** [comment]
It seems to me that this might be a bug of [ReSpec - webidl-oldschool ](https://github.com/w3c/respec/blob/develop/js/core/webidl-oldschool.js#L1095-L1100)

``` javascript
if (it.declaration) sn.text(", " + it.declaration, dt);
if (it.nullable) sn.text(", nullable", dt);
if (it.defaultValue) {
    sn.text(", defaulting to ", dt);
    sn.element("code", {}, dt, [sn.text(it.defaultValue)]);
}
```

Where `it.declaration` is always at least 9 characters long, [filled with spaces](https://github.com/w3c/respec/blob/develop/js/core/webidl-oldschool.js#L374-L375).

``` javascript
obj.declaration = match[1] ? match[1] : "";
obj.declaration += (new Array(9-obj.declaration.length)).join(" "); // fill string with spaces
```

I noticed that there is another file [ReSpec - webidl-contiguous ](https://github.com/w3c/respec/blob/develop/js/core/webidl-contiguous.js#L359-L387) doing the similar thing, probably a new version?

**Comment by RByers** [comment]
Hmm, maybe [file a respec bug](https://github.com/w3c/respec/issues)  (assuming there isn't already one) and see what they say there?

**Comment by RByers** [comment]
And / or maybe see if this code has changed, and if so who changed it.  If ReSpec had always behaved this way I think we probably would have noticed sooner...

**Comment by chong-z** [comment]
The code was changed on [Apr. 22, 2015](https://github.com/w3c/respec/commit/3bbe54f9adac0d72b962c836908f64901c80e9b9) by @dontcallmedom , might be the issue?

But since [webidl-oldschool is deprecated](https://github.com/w3c/respec/issues/395) I'm not sure if we should file a bug?

**Comment by chong-z** [comment]
Found the same issue here https://github.com/w3c/respec/issues/295 but closed due to deprecating and won't fix.

So what do we do, leave it, try a pull request or rewrite using new `<pre class="idl">` syntax (might take some time)?

**Comment by RByers** [comment]
@choniong Thanks!

The only right fix is to rewrite as `<pre class="idl">`.  This isn't urgent (only slightly ugly) so I say we just leave this issue open until someone feels like rewriting to the new format.

Sound good?

**Comment by dontcallmedom** [comment]
FWIW, https://github.com/w3c/respec/issues/295 is now fixed in respec (will be part of the next release, hopefully soon)

**Comment by chong-z** [comment]
@dontcallmedom Cool, thank you so much!

**Comment by RByers** [comment]
Given that issue has been fixed, there's little concrete benefit to rewriting the IDL so let's call this closed (but re-open if other reasons come up to re-write the IDL).
