### ISSUE TITLE
Need a reference for "CSS Pixel"

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#32]
The spec refers to "CSS Pixel" but there is no reference to the spec that defines that term.

**Comment by patrickhlauke** [comment]
assuming you mean a link to http://www.w3.org/TR/css3-values/#absolute-lengths right?

**Comment by RByers** [comment]
Yep, adding a reference to that sounds like a good idea to me.

**Comment by patrickhlauke** [comment]
Was going to do this, but have no idea how ReSpec automagically pulls in references. My gut feeling is that you'd simply add [[!CSS-VALUES]] somewhere near where we talk about CSS pixels...right?

[edit: nvm, just trying it out locally confirmed my hunch]
