### ISSUE TITLE
Include pageX/Y in the TouchInit dictionary

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#33]
Why are the pageX and pageY attributes not explicitly included in the [TouchInit dictionary](https://w3c.github.io/touch-events/#touch-interface)?

**Comment by mbrubeck** [comment]
Duplicate of #28.

**Comment by AFBarstow** [comment]
Thanks Matt! 
(If someone else asks about this, we should consider adding a non-normative note that explains the absence of these two attributes from the dictionary.)
