### ISSUE TITLE
Dangling sentence in touchcancel is confusing 

### ISSUE THREAD

**Issue by AFBarstow** [w3c/touch-events#35]
The following text in the description of cancelevent is "dangling" and needs some work:

[[
http://w3c.github.io/touch-events/#event-touchcancel

interactions. (e.g. The UA's native user interface, plug-ins) A user
]]

Options include: removing it; making it part of the preceding sentence; making it a stand-alone sentence (without parens).

**Comment by patrickhlauke** [comment]
Proposed change:

`A user agent may non-document area which is capable of handling user interactions (e.g. the UA's native user interface, or an area of the document which is managed by a plug-in). A user agent`

**Comment by AFBarstow** [comment]
@patrickhlauke "A UA may [something_appears_to_be_missing] non-document area ...".

**Comment by patrickhlauke** [comment]
oops, i messed up the copy-paste from my actual PR into the comment above. the sentence from the PR reads:

```
... leaving the document window into a non-document area which is capable of handling user
interactions (e.g. the UA's native user interface, or an area of the document which is
managed by a plug-in). A user agent may ...
```

**Comment by patrickhlauke** [comment]
not hearing any objections, i may be so bold as to merge this PR...
