### ISSUE TITLE
Note about PFWG's non-normative event mapping document

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/touch-events#4]
https://github.com/patrickhlauke/touch-events/commit/beaa75be016e1bf343e78658e8c0b68925d951a0 hides the current note (as it's been pointing to an empty document since the Touch Event spec's first publication, and to date there's no resolution on who/what/when this will be produced) as a comment. Either the comment needs to be completely removed from the document or the mapping document needs to be created and linked (by PFWG or the Touch/Pointer Events CG).

**Comment by RByers** [comment]
In review we decided to remove this entirely: d40797ac39a4f8347bb38b32ca4b558f56895bb1.  We can resurrect it if something changes here.  I think we can close this bug since we have no action to take in this group.  Feel free to re-open.

**Comment by patrickhlauke** [comment]
:+1:
