### ISSUE TITLE
TouchEventInit should inherit from EventModifierInit

### ISSUE THREAD

**Issue by dtapuska** [w3c/touch-events#40]
EventModifierInit is defined here: https://w3c.github.io/uievents/#idl-def-EventModifierInit

We should simply have TouchEventInit inherit from it and get rid of the alt, ctrl, meta, shift definitions in its dictionary in the Touch spec.

**Comment by RByers** [comment]
Ah, I thought I copied TouchEventInit from the MouseEventInit pattern, perhaps EventModifierInit was added after that?  But yes, let's do this right away before shipping the constructors in Chrome.  Thanks for catching this!

@choniong Assigning to myself to indicate that we intend to work on this (sadly github doesn't let you assign issues to people who don't have push access).
