### ISSUE TITLE
Deprecate createTouch and createTouchList?

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#48]
It seems there's general agreement among the vendors that constructors (#10) are the right way to create all types of DOM events.  Given that, we should consider explicitly deprecating createTouch and createTouchList.  We could do this similarly to how [UI Events has a legacy event initializers section](https://w3c.github.io/uievents/#legacy-event-initializers).

This also would give us a better place to add initTouchEvent (#29).

Let me know if anyone disagrees with this path forward as @choniong is actively working on this.

**Comment by AFBarstow** [comment]
Including the two Document.touch*() methods in a legacy appendix seems like the right thing to do (at  least for now ... and until their usage is close to zero if not zero).

**Comment by chong-z** [comment]
We have constructor for [Touch](https://w3c.github.io/touch-events/#touch-interface) and [TouchEvent](https://w3c.github.io/touch-events/#touchevent-interface), but I'm not so sure do we have constructor for [TouchList](https://w3c.github.io/touch-events/#touchlist-interface) as well?

**Comment by AFBarstow** [comment]
@choniong  I don't have a strong opinion on whether or not we need a constructor for TouchList. That said, I do think using constructors is "better" than adding a methods to Document.

Do we have any concrete data about D.cTL usage `in the wild`? If it isn't being used, perhaps there is compelling need to replace it with a constructor.

**Comment by chong-z** [comment]
@AFBarstow Sorry for the confusion, but actually I just want to check what developers should use after D.cTL was depreciated, is it ok that we depreciated something but there is no substitute? (given that we don't have constructor)

The use count for D.cTL is not tracked in Chromium so I don't have the information.

**Comment by chong-z** [comment]
Oh never mind, with `TouchEvent constructor` we actually don't need to create `TouchList` anymore...

**Comment by RByers** [comment]
Right, sorry for the confusion.  We discussed this a bit when we added the constructor - the 'sequence' API lets us just pass an array...
