### ISSUE TITLE
New ReSpec warning about inittouchevent

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#50]
Just noticed this warning (click the "1" at the top right):
`Found linkless <a> element with text 'inittouchevent' but no matching <dfn>.`

Presumably this came from 50f51ccacb0d5ad06f9cf6ed44f853d6a3616d10.  @choniong can you please take a look?  Perhaps ReSpec expects at least a tiny description for the API?

**Comment by chong-z** [comment]
Actually this issue can be tracked back to [Add a non-normative note about initTouchEvent - Apr 4, 2013](https://github.com/w3c/touch-events/commit/547b618#diff-4eabe02dca3a07b7f5b12418b1401717R690), where `initTouchEvent` was surround by `<a>` but the link was not defined....

ReSpec warning: `20. Found linkless <a> element with text 'inittouchevent' but no matching <dfn>.`

I think I can fix it by just remove `<a>` around `initTouchEvent`.
