### ISSUE TITLE
Expand mouse events/click note to specify these are usually only fired for tap

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/touch-events#63]
Currently the second note in http://w3c.github.io/touch-events/#mouse-events reads

> User agents will typically dispatch mouse and click events when there is only a single active touch point. Multi-touch interactions – involving two or more active touch points – will usually only generate touch events.

As per https://github.com/w3c/touch-events/issues/60#issuecomment-210205658 it would be good if in this (non-normative/informative) note there was a further mention that UAs typicially only dispatch these for tap/activation gestures (i.e. you don't get `mousemove` that track the movement of the single active touch point). @RByers raised a possible concern that the use of "tap gesture" may cause some issue, but if I recall correctly issues would only arise around other wording such as "double-tap to zoom" or similar.

Will draft a tiny tweak to this note next week when I'm back off holiday.

**Comment by RByers** [comment]
I see we're already using the non-normative text "The activation of an element (e.g., in some implementations, a tap)", so doing that elsewhere should be fine.  In PE we explicitly refer to "double tap gestures" in a note but add "Note that the methods for determining a tap or double-tap gesture are out of scope for this specification".

As long as we're just talking about a note here, I think we should just keep things as clear as possible and not be afraid to say "tap gesture" (unless/until someone objects).  So happy to see a PR to that effect :-)
