### ISSUE TITLE
Support Event.composed in Touch Events

### ISSUE THREAD

**Issue by hayatoito** [w3c/touch-events#66]
The context: w3c/webcomponents#513

Could someone give me advice how we should update Touch Events specification so it considers Event.composed?

Is a Pull Request a recommended way to reflect the conclusion at w3c/webcomponents#513
?

**Comment by cynthia** [comment]
I'm no longer a member of the group (lost affiliation), but historically a PR has been enough to get the ball rolling.

**Comment by patrickhlauke** [comment]
Yes, a PR (with a bit of explanation in the description) would be great, thanks.

**Comment by hayatoito** [comment]
Thanks. I have sent a PR: https://github.com/w3c/touch-events/pull/67
