### ISSUE TITLE
Clarify "deprecated in this specification"

### ISSUE THREAD

**Issue by RByers** [w3c/touch-events#80]
Our wording [here](https://w3c.github.io/touch-events/#extensions-to-the-document-interface) is vague.  We should probably say explicitly that they're included for compatibility but usage is discouraged as they are expected to be removed in the future.  In particular, I think we're pretty close to being able to remove them from Chrome - once that's been successful we'll discuss removal from the spec.

/cc @foolip

**Comment by EiraGe** [comment]
Chrome marked createTouch and createTouchList as deprecated from Chrome 66 and plan to complete remove them at Chrome 68. ([here](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/blink-dev/GLbUpUUnQzc/QBOQP4FiCgAJ))

Maybe it's time to remove the [`Legacy Event Initializers`](https://w3c.github.io/touch-events/#legacy-event-initializers) section. I create PR #96 to remove it.

**Comment by RByers** [comment]
Oh looks like there's one more reference to createTouchList in the note in section 5. I'd just suggest removing the note. Also an entry should be added to the 'changes since last publication' section at the end.

**Comment by patrickhlauke** [comment]
Done :)

**Comment by RByers** [comment]
And I see the update changes in #101 also, thank you!
