### ISSUE TITLE
Repo organisation

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/touch-events#9]
Not a major issue, but the current way this repo uses branches is not ideal, in my opinion. The fact that master is a completely different document (TE extensions) compared to the branches (TE) is confusing and non-standard. The two separate documents should perhaps be sibling documents in master instead? touch-events.html and touch-events-extensions.html?

**Comment by patrickhlauke** [comment]
(ideally, it would be two completely separate repos if possible...one for TE extensions, one for TE)

**Comment by RByers** [comment]
Addressed by my latest commits.
